### ISSUE TITLE
How to extend Velocity characters ？

### ISSUE THREAD

**Issue by li-car-fei** [wazenmai/MIDI-BERT#12]
hello, it is great work, if I want to use the information of note-velocity, what can I do ?

How to extend Velocity characters into dictionaries and data preprocessing ?

**Comment by wazenmai** [comment]
H @li-car-fei ,
If you want to include velocity characters into dictionaries, we have extend this version into our `v2` branch, you could follow the same preprocessing process as `CP` branch to convert midi songs into tokens including velocity information.

**Comment by li-car-fei** [comment]
> H @li-car-fei , If you want to include velocity characters into dictionaries, we have extend this version into our `v2` branch, you could follow the same preprocessing process as `CP` branch to convert midi songs into tokens including velocity information.

thank you，can you provide a function for generating midi through token sequence( including velocity )?
