### ISSUE TITLE
make midi file from wav fomat

### ISSUE THREAD

**Issue by NgvTue** [wazenmai/MIDI-BERT#4]
Pls I can't find the way make midi fomat file from wav.
I have researched from CP repo but your format is 'bar-position-pitch' different from CP-format.

**Comment by wazenmai** [comment]
Hi, @NgvTue 
We only use midi format file as our data, so we didn't support converting 'wav' to 'midi'.
If you want to convert your wav file to original CP representation, maybe you could find the information in https://github.com/YatingMusic/compound-word-transformer/blob/main/dataset/Dataset.md.

If you want to convert 'midi' to our cp-representation format, you could also find the information in https://github.com/wazenmai/MIDI-BERT/tree/main/prepare_data/CP.

Hope these information helps!

**Comment by sophia1488** [comment]
Hi, I've tested the conversion from 'wav' to 'midi' at [Onsets and Frames Transcription](https://goo.gl/magenta/onsets-frames-colab), and it works (though not 100% precise).

Like wazenmai said, after you have your midi file, you shall be able to do the conversion and get our simplified CP format data.
https://github.com/wazenmai/MIDI-BERT/blob/main/prepare_data/CP/main.py#L17
I just modified the code, you may run the command as below,
`python main.py --input_dir={your input directory}`
And you shall find your data at `../../data/CP/{your input directory}.npy`

Sorry for the inconvenience.
If I have time, I will make the code neater and more user-friendly for custom dataset.

Cheers!

**Comment by NgvTue** [comment]
Thank for quickly repiled, I will tested [Onsets and Frames Transcription](https://colab.research.google.com/notebooks/magenta/onsets_frames_transcription/onsets_frames_transcription.ipynb) as soon as.
Once again tks @sophia1488 and @wazenmai.
