### ISSUE TITLE
About the dataset.

### ISSUE THREAD

**Issue by liuyijiang1994** [wazenmai/MIDI-BERT#7]
Dear Author,
I find your work very interesting! 

Can you provide a combined data file?

Thanks!

**Comment by sophia1488** [comment]
Hi, I'm glad you like our work!
Please see the Readme.
https://github.com/wazenmai/MIDI-BERT#a-prepare-data

We only provide data in CP/remi tokens and the links to each dataset, since we don't own the dataset.

Cheers!

**Comment by liuyijiang1994** [comment]
> Hi, I'm glad you like our work! Please see the Readme. https://github.com/wazenmai/MIDI-BERT#a-prepare-data
> 
> We only provide data in CP/remi tokens and the links to each dataset, since we don't own the dataset.
> 
> Cheers!

Thanks!  For your reply and the excellent work!
